---
- name: Configurar LVM no Servidor de Arquivos
  hosts: arq
  become: yes
  tasks:
    - name: Instalar ferramentas de LVM
      apt:
        name: lvm2
        state: present

    - name: Criar Volume Group (VG) chamado vg_dados
      # Aqui ele agrupa os 3 discos extras que o Vagrant criou
      lvg:
        vg: vg_dados
        pvs: /dev/sdb,/dev/sdc,/dev/sdd
        pvresize: yes

    - name: Criar Logical Volume (LV) de 15GB
      # Usamos '15G' para bater com o roteiro. Se os discos somados 
      # tiverem menos que isso, ele usará o máximo disponível.
      lvol:
        vg: vg_dados
        lv: lv_arquivos
        size: 15G
        force: yes

    - name: Formatar o volume com sistema de arquivos EXT4
      filesystem:
        fstype: ext4
        dev: /dev/vg_dados/lv_arquivos

    - name: Criar diretório de montagem /mnt/arquivos
      file:
        path: /mnt/arquivos
        state: directory
        mode: '0755'

    - name: Montar o volume de forma persistente
      mount:
        path: /mnt/arquivos
        src: /dev/vg_dados/lv_arquivos
        fstype: ext4
        state: mounted
