---
- name: Configurar Servidor NFS (ARQ)
  hosts: arq
  become: yes
  tasks:
    - name: Instalar servidor NFS
      apt:
        name: nfs-kernel-server
        state: present

    - name: Criar usuário nfs-ifpb sem shell
      user:
        name: nfs-ifpb
        uid: 1500
        shell: /usr/sbin/nologin
        state: present

    - name: Criar diretório de exportação NFS
      file:
        path: /dados/nfs
        state: directory
        owner: nfs-ifpb
        group: ifpb
        mode: '0700' # '0700' garante escrita APENAS para o usuário nfs-ifpb, conforme o PDF

    - name: Configurar /etc/exports com mapeamento anonuid
      lineinfile:
        path: /etc/exports
        line: "/dados/nfs 192.168.56.0/24(rw,sync,all_squash,anonuid=1500,anongid=1500)" 
        create: yes
      notify: restart_nfs

  handlers:
    - name: restart_nfs
      service:
        name: nfs-kernel-server
        state: restarted

- name: Configurar Clientes NFS via Autofs
  hosts: db,app,cli
  become: yes
  tasks:
    - name: Instalar autofs e nfs-common
      apt:
        name:
          - autofs
          - nfs-common
        state: present

    - name: Configurar mapa mestre do Autofs
      lineinfile:
        path: /etc/auto.master
        line: "/var /etc/auto.nfs --timeout=60"

    - name: Criar arquivo de mapeamento auto.nfs
      copy:
        content: "nfs -fstype=nfs,rw,soft,tcp 192.168.56.136:/dados/nfs"
        dest: /etc/auto.nfs
      notify: restart_autofs

  handlers:
    - name: restart_autofs
      service:
        name: autofs
        state: restarted
