---
- name: Configuração Base de Infraestrutura
  hosts: servidores
  become: yes
  tasks:
    - name: Atualizar repositório e sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Ajustar Zona de Tempo para America/Recife
      timezone:
        name: America/Recife

    - name: Instalar Chrony (NTP)
      apt:
        name: chrony
        state: present

    - name: Configurar Servidor NTP pool.ntp.br
      lineinfile:
        path: /etc/chrony/chrony.conf
        regexp: '^pool '
        line: 'pool pool.ntp.br iburst'
      notify: restart_chrony

    - name: Criar grupo ifpb
      group:
        name: ifpb
        state: present

    - name: Criar os usuários pedro e vercosa
      user:
        name: "{{ item }}"
        group: ifpb
        shell: /bin/bash
      loop:
        - pedro
        - vercosa

    # O módulo authorized_key cria a pasta .ssh, o arquivo authorized_keys,
    # aplica o chmod correto (600) e o chown do usuário automaticamente!
    - name: Autorizar chave pública para acesso SSH dos usuários
      ansible.posix.authorized_key:
        user: "{{ item }}"
        state: present
        # lookup('file', ...) busca uma chave pública que está na sua máquina real (hospedeiro)
        # Substitua pelo caminho da sua chave pública real ou de um arquivo id_rsa.pub do seu projeto
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      loop:
        - pedro
        - vercosa

    - name: Instalar cliente NFS em todas as máquinas
      apt:
        name: nfs-common
        state: present

    - name: Permitir que usuários do grupo ifpb tenham acesso de root usando sudo
      copy:
        content: "%ifpb ALL=(ALL) ALL"
        dest: /etc/sudoers.d/ifpb
        mode: '0440'

    - name: Configurar regras do SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
        - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
        - { regexp: '^#?AllowGroups', line: 'AllowGroups vagrant ifpb' } # Restrição de grupo

    - name: Configurar Mensagem de Saudação Exata (Banner SSH)
      copy:
        content: "Acesso apenas para pessoas com autorização expressa!!!"
        dest: /etc/issue.net

    - name: Apontar o Banner no sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?Banner'
        line: 'Banner /etc/issue.net'
      notify: restart_ssh

  handlers:
    - name: restart_chrony
      service:
        name: chrony
        state: restarted

    - name: restart_ssh
      service:
        name: ssh
        state: restarted
