---
- name: Hardening de Segurança SSH
  hosts: servidores
  become: yes
  tasks:
    - name: Configurar Banner de Boas-vindas (MOTD)
      copy:
        content: |
          *******************************************************
          SISTEMA MONITORADO - ACESSO RESTRITO (PEDRO E VERCOSA)
          QUALQUER ATIVIDADE SUSPEITA SERÁ REGISTRADA.
          *******************************************************
        dest: /etc/motd

    - name: Desativar login de root via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Reiniciar serviço SSH
      service:
        name: ssh
        state: restarted
