---
- name: Instalar Banco de Dados
  hosts: db
  become: yes
  tasks:
    - name: Instalar MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Garantir que MariaDB está rodando
      service:
        name: mariadb
        state: started

- name: Instalar Servidor Web
  hosts: app
  become: yes
  tasks:
    - name: Instalar Apache2
      apt:
        name: apache2
        state: present

    - name: Criar index.html personalizado com dados do escopo
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="pt-br">
          <head>
              <meta charset="UTF-8">
              <title>Projeto 01 - DevOps com Vagrant e Ansible</title>
          </head>
          <body>
              <h1>Projeto 01 - DevOps com Vagrant e Ansible</h1>
              <h2>Disciplina: Administração de Sistemas Abertos</h2>
              
              <h3>Descrição do Projeto:</h3>
              <p>Este projeto consiste na automatização e provisionamento de uma infraestrutura virtualizada multihost utilizando Vagrant e Ansible. O ambiente engloba a configuração automatizada de serviços essenciais de rede e armazenamento (como DHCP, DNS, LVM e NFS), além de servidores dedicados de banco de dados e aplicação web de forma segura e resiliente.</p>
              
              <h3>Equipe de Desenvolvimento:</h3>
              <ul>
                  <li><strong>Pedro</strong> (Matrícula: XXX36)</li>
                  <li><strong>Vercosa</strong> (Matrícula: YYY36)</li>
              </ul>
          </body>
          </html>
        dest: /var/www/html/index.html

- name: Configurar Host Cliente (CLI)
  hosts: cli
  become: yes
  tasks:
    - name: Instalar Firefox e Xauth
      apt:
        name:
          - firefox-esr
          - xauth
        state: present

    - name: Permitir encaminhamento X11 no SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?X11Forwarding'
        line: 'X11Forwarding yes'
      notify: restart_ssh

  handlers:
    - name: restart_ssh
      service:
        name: ssh
        state: restarted
