---
- name: Configurar Infraestrutura de Rede (ARQ)
  hosts: arq
  become: yes
  tasks:
    - name: Instalar DHCP e DNS (Bind9)
      apt:
        name: 
          - isc-dhcp-server
          - bind9
        state: present

    - name: Configurar Interface do DHCP
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="eth1"'

    - name: Configurar escopo do DHCP (dhcpd.conf)
      copy:
        content: |
          option domain-name "pedro.vercosa.devops";
          option domain-name-servers 192.168.56.136;
          default-lease-time 180; # Solicitado no PDF
          max-lease-time 3600;    # Solicitado no PDF
          authoritative;

          subnet 192.168.56.0 netmask 255.255.255.0 {
            range 192.168.56.50 192.168.56.100; # Solicitado no PDF
            option routers 192.168.56.1;       # Gateway solicitado no PDF
          }

          # IP Estático para o DB por MAC (XY = 37)
          host db_server {
            hardware ethernet 08:00:27:AA:AA:01;
            fixed-address 192.168.56.137;
          }

          # IP Estático para o APP por MAC (YY = 38)
          host app_server {
            hardware ethernet 08:00:27:AA:AA:02;
            fixed-address 192.168.56.138;
          }
        dest: /etc/dhcp/dhcpd.conf
      notify: restart_dhcp

  handlers:
    - name: restart_dhcp
      service:
        name: isc-dhcp-server
        state: restarted
