---
- name: Segurança do SSH
  hosts: servidores
  become: yes
  tasks:
    - name: Desativar login de root via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
    
    - name: Adicionar Banner de Boas-vindas
      copy:
        content: "BEM-VINDO AO SERVIDOR DE PEDRO E VERCOSA. ACESSO MONITORADO."
        dest: /etc/motd

    - name: Reiniciar SSH para aplicar
      service:
        name: ssh
        state: restarted
